language: ruby

rvm:
  - 2.2.2

services: postgresql

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - psql -c 'create database hitchlog_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rspec spec --format progress
  - bundle exec cucumber features --format progress

deploy:
  provider: heroku
  strategy: git
  branch:
    - develop
    - master
  app:
    master: hitchlog
    develop: hitchlog-staging
    geomap: hitchlog-staging
  api_key:
    secure: FFualFIJXLj4TukM6ytjtVpXaao1YYLP4R+LUQBFKiLmyueluXE971xeMt1on1E5fLDF+JNxiZN/umukeIxXcPlVqMB5R50A3AaSvhniJ9YMoW11/qosTOAsDeWNz5tEptlH+ztvTHKm4vToitWn2vqRcYu+ZNuEt+wG3XM4cRY=
  run:
    - "rake db:migrate"
  rvm: 2.2.2

