development:
  adapter: postgresql
  database: hitchlog_development
  encoding: UTF8

test: &test
  adapter: postgresql
  database: hitchlog_test
  encoding: UTF8

production:
  adapter: postgresql
  database: hitchlog_production
  encoding: UTF8


cucumber:
  <<: *test