base_locale: en
locales: [en]
data:
  read:
    - config/locales/%{locale}.yml
    - config/locales/will_paginate.%{locale}.yml
    - config/locales/devise.%{locale}.yml
    - config/locales/simple_form.%{locale}.yml

  write:
    - ['{devise, will_paginate, simple_form}.*', 'config/locales/\1.%{locale}.yml']

  yaml:
    write:
      line_width: -1

search:
  exclude:
    - app/assets/images
    - app/assets/fonts

ignore_unused:
  - 'activerecord.attributes.*'
  - '{devise,errors,datetime,simple_form,will_paginate}.*'
  - 'helper.travelling_with_{0,1,2,3}'

